### ISSUE TITLE
Street names looks ugly

### ISSUE THREAD

**Issue by klokan** [openmaptiles/dark-matter-gl-style#1]
Deep zooms on dark matter reveals ugly styled street names:

<img width="807" alt="screen shot 2017-01-06 at 10 28 49" src="https://cloud.githubusercontent.com/assets/59284/21713618/1e32c802-d3fb-11e6-9826-e84e32cd8970.png">
vs
<img width="946" alt="screen shot 2017-01-06 at 10 28 12" src="https://cloud.githubusercontent.com/assets/59284/21713626/2714cdb2-d3fb-11e6-821f-fe56f9f072bb.png">

It looks unfinished.

Can we fix this, please?

**Comment by lukasmartinelli** [comment]
Fixed. Dark Matter needs some more work in general actually.

![screenshot from 2017-01-06 11-09-01](https://cloud.githubusercontent.com/assets/1288339/21714680/8cd6685e-d400-11e6-9af3-f5bd49183cfd.png)
