### ISSUE TITLE
Display both native and English names (where appropriate)?

### ISSUE THREAD

**Issue by chrisbartley** [openmaptiles/dark-matter-gl-style#4]
Apologies if this is a dumb question and/or I'm asking in the wrong place, but, in the preview of this style at https://openmaptiles.org/styles/ country names appear in both the native language and English, where appropriate (see screenshot).  For example, "China" is shown in both English and Chinese.  But, "United Kingdom" is shown only in English.  That's great, and exactly what I want.  However, when editing in Maputnik (by choosing "Edit in Maputnik" from that page), the country names are shown only in English.  Is this is limitation of Maputnik, and I should just be using some other style editor (and, if so, what?), or is the style actually different, or something other explanation?  

FWIW, the same problem exists in all the other "both name" styles I found on that page--it's not limited to Dark Matter.

Thanks for your help! 

<img width="810" alt="screen shot 2017-11-27 at 4 15 24 pm" src="https://user-images.githubusercontent.com/86031/33289660-402ecd1e-d38e-11e7-8df5-016204a65ae8.png">

**Comment by jirik** [comment]
In the master branch of this repo we intentionally have only one layer per label type to keep things simple. To create more complex labels as those you can see in the preview, we are automatically "decorating" the style, meaning duplicating some label layers, setting new "text-field" and appropriate filters.

**Example**
- Source: https://github.com/openmaptiles/dark-matter-gl-style/blob/master/style.json
- Decorated: https://github.com/openmaptiles/dark-matter-gl-style/blob/gh-pages/style-cdn.json

If you want to try it on backend, you can inspire here:
- https://github.com/klokantech/gl-style-package-spec/commit/931d04a843e7af483ad6d59518d5f4c5ef14f5c4
- https://github.com/openmaptiles/dark-matter-gl-style/blob/master/lang-fallback.json

Frontend usage:
- https://openmaptiles.org/languages/native/#6.76/47.77/9.633

**Comment by denishuvelle** [comment]
Hi @jirik ,

It's pretty old but I can't find any info on the correct usage :(

For an existing style, how do we use lang-fallback.json?
