### ISSUE TITLE
Invalid Key - 403 error

### ISSUE THREAD

**Issue by brianbancroft** [openmaptiles/dark-matter-gl-style#7]
Hi there, 

When I attempt to browse the map in this repo, the tiles fail to render, and I keep getting 403-errors - `Invalid key`. 

https://openmaptiles.github.io/dark-matter-gl-style/#0.69/-0/-0

Would this be something you'd be able to resolve?

Best wishes!

**Comment by daliborjanak** [comment]
Hi, I'm changing the keys and origins so it was broken here for some time. Now it is fixed, thanks for the report

**Comment by brianbancroft** [comment]
Thanks!
